# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktunnel < Formula
  desc "Network tunneling tool for kubernetes."
  homepage "https://github.com/omrikiei/ktunnel"
  version "2.4.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/omrikiei/ktunnel/releases/download/v2.4.0/ktunnel_2.4.0_Darwin_x86_64.tar.gz"
      sha256 "de851697fac19f56bca135d313718f268157d6b2a63f9dd0cf58323a96f16bf9"

      define_method(:install) do
        bin.install "ktunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/omrikiei/ktunnel/releases/download/v2.4.0/ktunnel_2.4.0_Darwin_arm64.tar.gz"
      sha256 "9bbe18fd0698f84b77ddbde9050f543ec73da3d748ad2d0a59c05d6b2fd60d53"

      define_method(:install) do
        bin.install "ktunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/omrikiei/ktunnel/releases/download/v2.4.0/ktunnel_2.4.0_Linux_x86_64.tar.gz"
      sha256 "a6520cc2032773cd3c45352839412da15946ab34929ed038900cf04212190300"
      define_method(:install) do
        bin.install "ktunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/omrikiei/ktunnel/releases/download/v2.4.0/ktunnel_2.4.0_Linux_arm64.tar.gz"
      sha256 "aedace0d5e2899b1d292d65c2fe04854f74deeb21ca5306a8b37cceb6e8393ab"
      define_method(:install) do
        bin.install "ktunnel"
      end
    end
  end

  test do
    system "#{bin}/ktunnel", "version"
  end
end
