# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktunnel < Formula
  desc "Network tunneling tool for kubernetes."
  homepage "https://github.com/omrikiei/ktunnel"
  version "2.0.2"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/omrikiei/ktunnel/releases/download/v2.0.2/ktunnel_2.0.2_Darwin_x86_64.tar.gz"
      sha256 "a0b4b42068bcb54d525e036a2538bf79a45f012ea8f2ed31b5921afe352e971b"

      define_method(:install) do
        bin.install "ktunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/omrikiei/ktunnel/releases/download/v2.0.2/ktunnel_2.0.2_Darwin_arm64.tar.gz"
      sha256 "3c27998eabdb88cc5f46726a551d02a31925e398630e335aa283a92d9491d9a1"

      define_method(:install) do
        bin.install "ktunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/omrikiei/ktunnel/releases/download/v2.0.2/ktunnel_2.0.2_Linux_x86_64.tar.gz"
      sha256 "c4d744291c195ee3d0b631ac0430facd37d6c0b112dcfd1007ff1f735d8198cd"
      define_method(:install) do
        bin.install "ktunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/omrikiei/ktunnel/releases/download/v2.0.2/ktunnel_2.0.2_Linux_arm64.tar.gz"
      sha256 "8b390403e94e2574b7504608b6fd8a50aa4cb2154b5858a8dec35f303588677b"
      define_method(:install) do
        bin.install "ktunnel"
      end
    end
  end

  test do
    system "#{bin}/ktunnel", "version"
  end
end
